### ISSUE TITLE
SELinux denies execution of mail-*-notification.sh

### ISSUE THREAD

**Issue by shiz0** [Icinga/icinga2#4997]
CentOS7
uname -a
Linux hostname 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

getenforce
Enforcing

Latest packages are installed via yum:
yum list installed | grep icinga
icinga-rpm-release.noarch        7-2.el7.centos           @icinga-stable-release
icinga2.x86_64                   2.6.1-1.el7.centos       @icinga-stable-release
icinga2-bin.x86_64               2.6.1-1.el7.centos       @icinga-stable-release
icinga2-common.x86_64            2.6.1-1.el7.centos       @icinga-stable-release
icinga2-ido-mysql.x86_64         2.6.1-1.el7.centos       @icinga-stable-release
icinga2-libs.x86_64              2.6.1-1.el7.centos       @icinga-stable-release
icinga2-selinux.x86_64           2.6.1-1.el7.centos       @icinga-stable-release
icingacli.noarch                 2.4.1-1.el7.centos       @icinga-stable-release
icingaweb2.noarch                2.4.1-1.el7.centos       @icinga-stable-release
icingaweb2-common.noarch         2.4.1-1.el7.centos       @icinga-stable-release
icingaweb2-selinux.noarch        2.4.1-1.el7.centos       @icinga-stable-release
icingaweb2-vendor-HTMLPurifier.noarch
                                 4.8.0-1.el7.centos       @icinga-stable-release
icingaweb2-vendor-JShrink.noarch 1.1.0-1.el7.centos       @icinga-stable-release
icingaweb2-vendor-Parsedown.noarch
                                 1.6.0-1.el7.centos       @icinga-stable-release
icingaweb2-vendor-dompdf.noarch  0.7.0-1.el7.centos       @icinga-stable-release
icingaweb2-vendor-lessphp.noarch 0.4.0-1.el7.centos       @icinga-stable-release
icingaweb2-vendor-zf1.noarch     1.12.20-1.el7.centos     @icinga-stable-release
php-Icinga.noarch                2.4.1-1.el7.centos       @icinga-stable-release
vim-icinga2.x86_64               2.6.1-1.el7.centos       @icinga-stable-release

lz /etc/icinga2/scripts/
drwxr-x---. icinga icinga system_u:object_r:nagios_notification_plugin_exec_t:s0 .
drwxr-x---. root   icinga system_u:object_r:icinga2_etc_t:s0 ..
-rwxr-xr-x. icinga icinga system_u:object_r:nagios_notification_plugin_exec_t:s0 mail-host-notification.sh
-rwxr-xr-x. icinga icinga system_u:object_r:nagios_notification_plugin_exec_t:s0 mail-service-notification.sh

When trying to send mail notification, access to the scripts is denied by SELinux.
(See attached debug.log)
Verified by temp disabling SELinux ("setenforce 0" enables notifications)

No entries in audit.log
Everything else (commands, checks etc.) seems to be wirking fine.

[debuglog.txt](https://github.com/Icinga/icinga2/files/770897/debuglog.txt)
[icinga2_--version.txt](https://github.com/Icinga/icinga2/files/770898/icinga2_--version.txt)

**Comment by gunnarbeutner** [comment]
@dgoetz Can you please have a look at this? :)

**Comment by shiz0** [comment]
Temporary fix (apart from disabling SELinux altogether) is setting the notifications domain to permissive:
$ sudo semanage permissive -a nagios_notification_plugin_t

**Comment by dgoetz** [comment]
Can you have a look into audit.log (or if auditd is not running /var/log/messages) if there is a message logged when set to permissive? If not it must be some message already marked as dontaudit, so please execute "semodule -DB" to get all audit messages logged (afterwards execute "semodule -B" to not spam your logs).

Otherwise I think it is perhaps already fixed with unmerged branch feature/improve-selinux-13167 (https://github.com/Icinga/icinga2/issues/4781).

**Comment by shiz0** [comment]
After "semodule -DB" the following is logged when sending a custom host notification: 
Domain enforcing:
[auditlog_enforcing.txt](https://github.com/Icinga/icinga2/files/771078/auditlog_enforcing.txt)
Domain permissive:
[auditlog.txt](https://github.com/Icinga/icinga2/files/771079/auditlog.txt)

**Comment by dgoetz** [comment]
It denies read on directory above which is already addressed and it tries to read /etc/passwd which I hope is not required, but I could allow.

Can you test again with the updated policy? Michael already merged it, so its available from snapshot packages soon, or by build it on your own.

**Comment by shiz0** [comment]
After enabling the snapshot repo and updating via yum to:
icinga2.x86_64 0:2.6.2-1.snapshot201702131650.el7.centos
icinga2-bin.x86_64 0:2.6.2-1.snapshot201702131650.el7.centos
icinga2-common.x86_64 0:2.6.2-1.snapshot201702131650.el7.centos
icinga2-ido-mysql.x86_64 0:2.6.2-1.snapshot201702131650.el7.centos
icinga2-libs.x86_64 0:2.6.2-1.snapshot201702131650.el7.centos
icinga2-selinux.x86_64 0:2.6.2-1.snapshot201702131650.el7.centos
vim-icinga2.x86_64 0:2.6.2-1.snapshot201702131650.el7.centos
[auditlog_enforcing_after_upd.txt](https://github.com/Icinga/icinga2/files/773885/auditlog_enforcing_after_upd.txt)

These are the permissions:

lz /etc/icinga2/scripts/
drwxr-x---. icinga icinga system_u:object_r:icinga2_etc_t:s0 .
drwxr-x---. root   icinga system_u:object_r:icinga2_etc_t:s0 ..
-rwxr-xr-x. icinga icinga system_u:object_r:nagios_notification_plugin_exec_t:s0 mail-host-notification.sh
-rwxr-xr-x. icinga icinga system_u:object_r:nagios_notification_plugin_exec_t:s0 mail-service-notification.sh

and notifications get sent out.
This is the audit.log while sending a custom notification via IcingaWeb2:

**Comment by dgoetz** [comment]
You are still running with dontaudit rules disabled, please run "semodule -B" to get rid of the messages. (Or simply revert your snapshot.)

So policy is fine with the changes which will be included in the next release.

**Comment by shiz0** [comment]
Yes, I ran "semodule -DB" before on purpose to get the log messages for you.
I will now revert to the VM-Snapshot I created before enabling the snapshot repo and continue to run the domain in permissive mode, until the changes make it to the stable release.
Thank you. :+1:

**Comment by gunnarbeutner** [comment]
Am I correct in assuming that this has been solved? Feel free to re-open this ticket if there's still something left to do here. :)

**Comment by helgein** [comment]
Here
https://monitoring-portal.org/index.php?thread/40402-selinux-is-blocking-icinga2-notifications/&postID=247207#post247207
is a persom running 2.6.3 that still sees the same problem.

**Comment by craigafinch** [comment]
@helgein @gunnarbeutner Please re-open; the problem persists with release 2.6.3. I am running the latest CentOS 7 with SELinux enforcing. Strangely, Icinga2 was able to send email notifications successfully for a few days, and then just stopped. I did not change any SELinux configurations on the server during that time. I've tried reinstalling icinga2-selinux, and that didn't help. 

Versions:
```
icinga2.x86_64                    2.6.3-1.el7.centos      @icinga-stable-release
icinga2-bin.x86_64                2.6.3-1.el7.centos      @icinga-stable-release
icinga2-common.x86_64             2.6.3-1.el7.centos      @icinga-stable-release
icinga2-ido-mysql.x86_64          2.6.3-1.el7.centos      @icinga-stable-release
icinga2-libs.x86_64               2.6.3-1.el7.centos      @icinga-stable-release
icinga2-selinux.x86_64            2.6.3-1.el7.centos      @icinga-stable-release
icingacli.noarch                  2.4.1-1.el7.centos      @icinga-stable-release
icingaweb2.noarch                 2.4.1-1.el7.centos      @icinga-stable-release
icingaweb2-common.noarch          2.4.1-1.el7.centos      @icinga-stable-release
icingaweb2-vendor-HTMLPurifier.noarch
                                  4.8.0-1.el7.centos      @icinga-stable-release
icingaweb2-vendor-JShrink.noarch  1.1.0-1.el7.centos      @icinga-stable-release
icingaweb2-vendor-Parsedown.noarch
                                  1.6.0-1.el7.centos      @icinga-stable-release
icingaweb2-vendor-dompdf.noarch   0.7.0-1.el7.centos      @icinga-stable-release
icingaweb2-vendor-lessphp.noarch  0.4.0-1.el7.centos      @icinga-stable-release
icingaweb2-vendor-zf1.noarch      1.12.20-1.el7.centos    @icinga-stable-release
php-Icinga.noarch                 2.4.1-1.el7.centos      @icinga-stable-release
vim-icinga2.x86_64                2.6.3-1.el7.centos      @icinga-stable-release
```

My Icinga2 logs show:

```
[2017-05-03 03:24:55 +0000] warning/PluginNotificationTask: Notification command for object 'some-host-name!procs' (PID: 31028, arguments: '/etc/icinga2/scripts/mail-service-notification.sh') terminated with exit code 126, output: /bin/sh: /etc/icinga2/scripts/mail-service-notification.sh: Permission denied
```
Audit logs:

```
----
time->Wed May  3 03:24:55 2017
type=SYSCALL msg=audit(1493781895.113:14940): arch=c000003e syscall=2 success=no exit=-13 a0=2b1f0145f432 a1=80000 a2=1b6 a3=24 items=0 ppid=30293 pid=31029 auid=4294967295 uid=996 gid=993 euid=996 suid=996 fsuid=996 egid=993 sgid=993 fsgid=993 tty=(none) ses=4294967295 comm="mail-service-no" exe="/usr/bin/bash" subj=system_u:system_r:nagios_notification_plugin_t:s0 key=(null)
type=AVC msg=audit(1493781895.113:14940): avc:  denied  { read } for  pid=31029 comm="mail-service-no" name="passwd" dev="sda1" ino=1780 scontext=system_u:system_r:nagios_notification_plugin_t:s0 tcontext=system_u:object_r:passwd_file_t:s0 tclass=file
----
time->Wed May  3 03:24:55 2017
type=SYSCALL msg=audit(1493781895.113:14941): arch=c000003e syscall=2 success=no exit=-13 a0=13c6d40 a1=0 a2=4 a3=4 items=0 ppid=30293 pid=31029 auid=4294967295 uid=996 gid=993 euid=996 suid=996 fsuid=996 egid=993 sgid=993 fsgid=993 tty=(none) ses=4294967295 comm="mail-service-no" exe="/usr/bin/bash" subj=system_u:system_r:nagios_notification_plugin_t:s0 key=(null)
type=AVC msg=audit(1493781895.113:14941): avc:  denied  { search } for  pid=31029 comm="mail-service-no" name="icinga2" dev="sda1" ino=7071 scontext=system_u:system_r:nagios_notification_plugin_t:s0 tcontext=system_u:object_r:icinga2_etc_t:s0 tclass=dir
----
time->Wed May  3 03:24:55 2017
type=SYSCALL msg=audit(1493781895.115:14942): arch=c000003e syscall=2 success=no exit=-13 a0=2ba302d7b432 a1=80000 a2=1b6 a3=24 items=0 ppid=30293 pid=31028 auid=4294967295 uid=996 gid=993 euid=996 suid=996 fsuid=996 egid=993 sgid=993 fsgid=993 tty=(none) ses=4294967295 comm="mail-service-no" exe="/usr/bin/bash" subj=system_u:system_r:nagios_notification_plugin_t:s0 key=(null)
type=AVC msg=audit(1493781895.115:14942): avc:  denied  { read } for  pid=31028 comm="mail-service-no" name="passwd" dev="sda1" ino=1780 scontext=system_u:system_r:nagios_notification_plugin_t:s0 tcontext=system_u:object_r:passwd_file_t:s0 tclass=file
----
time->Wed May  3 03:24:55 2017
type=SYSCALL msg=audit(1493781895.115:14943): arch=c000003e syscall=2 success=no exit=-13 a0=d9bd40 a1=0 a2=68 a3=4 items=0 ppid=30293 pid=31028 auid=4294967295 uid=996 gid=993 euid=996 suid=996 fsuid=996 egid=993 sgid=993 fsgid=993 tty=(none) ses=4294967295 comm="mail-service-no" exe="/usr/bin/bash" subj=system_u:system_r:nagios_notification_plugin_t:s0 key=(null)
type=AVC msg=audit(1493781895.115:14943): avc:  denied  { search } for  pid=31028 comm="mail-service-no" name="icinga2" dev="sda1" ino=7071 scontext=system_u:system_r:nagios_notification_plugin_t:s0 tcontext=system_u:object_r:icinga2_etc_t:s0 tclass=dir
----
```

Script context and permissions:

```
-rwxr-xr-x. root root system_u:object_r:nagios_notification_plugin_exec_t:s0 /etc/icinga2/scripts/mail-service-notification.sh
```

The last notification that my server successfully sent went out on April 23. Here are the packages I've installed or updated since then:

```
Apr 25 05:57:29 Installed: python2-pycryptodomex.x86_64 3.4.3-1.el7
Apr 25 05:57:32 Updated: salt.noarch 2016.11.4-1.el7
Apr 25 05:57:33 Updated: salt-minion.noarch 2016.11.4-1.el7
Apr 25 05:57:33 Updated: php-pecl-igbinary.x86_64 2.0.4-1.el7.remi.5.6
Apr 26 06:49:40 Updated: ImageMagick6-libs.x86_64 6.9.8.4-1.el7.remi
Apr 28 05:37:55 Updated: google-compute-engine.noarch 2.3.6-0.1493230884.el7
Apr 30 05:19:27 Updated: php-jsonlint.noarch 1.6.0-1.el7
May 02 07:22:36 Updated: php-pecl-xdebug.x86_64 2.5.3-2.el7.remi.5.6
```

**Comment by dgoetz** [comment]
The fix was not backported, so it is not solved in 2.6.3, but will be at least in 2.7.0. For now I would recommend manually updating the policy or `semanage permissive -a nagios_notification_plugin_t` to set only this context in permissive mode.

@gunnarbeutner or @dnsmichi: Can we backport it to 2.6.4 if release date is much sooner than 2.7.0?

**Comment by dnsmichi** [comment]
Test the snapshot packages first and report back if they really solve the issue.

**Comment by mkayontour** [comment]
Any Updates on this bug?

**Comment by lazyfrosch** [comment]
@mkayontour this is quite old and the root cause here should be solved.

If not please open a new issue describing your problem, mentioning this issues here.
