### ISSUE TITLE
Syntax error in notification scripts (Snapshot packages only)

### ISSUE THREAD

**Issue by mcktr** [Icinga/icinga2#7648]
## Describe the bug

The notification scripts from the snapshot packages have some syntax errors:

```
./mail-host-notification.sh: 112: ./mail-host-notification.sh: Syntax error: "(" unexpected (expecting "then")
./mail-service-notification.sh: 116: ./mail-service-notification.sh: Syntax error: "(" unexpected (expecting "then")
```

This originates from #6822. Reverting the changes leads to the following syntax error:

```
./mail-host-notification.sh: 107: ./mail-host-notification.sh: Syntax error: redirection unexpected
./mail-service-notification.sh: 111: ./mail-service-notification.sh: Syntax error: redirection unexpected
```

This originates from #6369. Reverting the changes leads to another syntax error which is reported in #7609 (and will be fixed with #7647).

I've only tested this on Debian 10 and 9, I don't know how CentOS for example behaves. 

## To Reproduce

Test this in a docker container

1. Start the container
```
sudo docker run -ti -h deb10i2m1s debian:buster /bin/bash
```
2. Install Icinga 2 snapshot packages
```
apt-get update && apt-get upgrade -y && apt-get install wget gnupg2 ca-certificates vim apt-transport-https -y && echo "deb https://packages.icinga.com/debian/ icinga-buster-snapshots main" > /etc/apt/sources.list.d/icinga.list && wget -O - https://packages.icinga.com/icinga.key | apt-key add - && apt-get update && apt-get install icinga2 monitoring-plugins -y && /usr/lib/icinga2/prepare-dirs
```
3. Move into the `scripts` directory
```
cd /etc/icinga2/scripts
```
4. Execute the notification scripts

Host notification script:
```
./mail-host-notification.sh -d '2019-11-06 14:50:00 +0000' -l 'server@example.com' -n 'server@exmaple.com' -o 'CRITICAL - Host Unreachable (server@exmaple.com)' -r 'user@example.com' -s 'DOWN' -t 'CUSTOM'
```

Service notification script:
```
./mail-service-notification.sh -d '2019-11-06 14:50:00 +0000' -l 'server@example.com' -n 'server@exmaple.com' -o 'CRITICAL - Host Unreachable (server@exmaple.com)' -r 'user@example.com' -s 'DOWN' -t 'CUSTOM' -u 'DISK' -e 'DISK'
```

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): v2.11.1-332-gc23112313
* Operating System and version: Debian 10 & Debian 9

**Comment by dnsmichi** [comment]
Ah, Debian and dash instead of bash.

**Comment by tpo** [comment]
> Ah, Debian and dash instead of bash

If icinga needs bash as shell, then, I'd suggest, **it should say so**:

<pre>
diff -u mail-service-notification.sh.broken mail-service-notification.sh
--- mail-service-notification.sh.broken 2019-11-27 11:28:06.499713871 +0100
+++ mail-service-notification.sh        2019-11-27 11:17:10.171689017 +0100
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # Icinga 2 | (c) 2012 Icinga GmbH | GPLv2+
 # Except of function urlencode which is Copyright (C) by Brian White (brian@aljex.com) used under MIT license
</pre>

We haven't had mail notifications for a few weeks. It took me a day to find the problem:

<pre>
$ /etc/icinga2/scripts/mail-service-notification.sh -d 2019-11-27 -e fooservice -l fooserver -n FooServer -o "shit happened" -r icinga@example.org -s kaput -t alert -u FooService
/etc/icinga2/scripts/mail-service-notification.sh: 153: [: unexpected operator
</pr>

<pre>
diff -u mail-service-notification.sh.orig mail-service-notification.sh
--- mail-service-notification.sh.broken   2019-11-27 11:17:02.091688311 +0100
+++ mail-service-notification.sh        2019-11-27 11:17:10.171689017 +0100
@@ -152,7 +152,7 @@
 
 ## Check whether verbose mode was enabled and log to syslog.
-if [ "$VERBOSE" == "true" ] ; then
+if [ "$VERBOSE" = "true" ] ; then
   logger "$PROG sends $SUBJECT => $USEREMAIL"
 fi
</pre>

But as usual, when there's a problem there's not only one problem. In this case it took me so long to debug this, because the icinga logs are absolutely silent if the call that script and the script breaks and explodes.

So I'd like to very kindly ask you Michael: would you please have icinga log an error when the email sending script colapses at the work place? That would be very nice!

Also, this is quite a **critical bug** for us since our monitoring system was very silent for a few weeks and we were rejoicing how smoothly our infrastructure is running while in reality CPUs were burning, zombie backups causing fear and loathing and packets were causing environmental havoc.

Thanks for icinga Michael!

**Comment by dnsmichi** [comment]
We shouldn't move this to bash, but rather find a way to keep this compatible. I don't like shell programming much, therefore I'm kindly asking for help from anyone capable of creating a fix for the problem here.

The mentioned problem is fixed with #7647. 

When Icinga cannot execute a notification script or check plugin, it logs a warning message.
https://github.com/Icinga/icinga2/blob/master/lib/methods/pluginnotificationtask.cpp#L64

Still, if the notification scripts don't provoke such errors, you can always modify them. That's also the reason why they are put into `/etc/icinga2/scripts` and are not overridden on package updates, if the user modified them - to leave space for own logging, improvements and what not.

Cheers,
Michael

**Comment by tpo** [comment]
> what you wrote

Ack! Thanks a lot!

However, for whatever reason, icinga did **not** log the problem.

Weirdly enough, now that I've applied the fix for the broken comparison operator icinga *does* log that warning message. So I'm seeing the next problem:

<pre>
/var/log/icinga2/icinga2.log:[2019-11-27 12:00:24 +0100] warning/PluginNotificationTask: Notification command for checkable 'foohost!fooservice' and notification 'foohost!fooservice!mail-icingaadmin' (PID: 18306, arguments: '/etc/icinga2/scripts/mail-service-notification.sh') terminated with exit code 1, output: Required parameter 'HOSTNAME' is missing.
</pre>

Which means, since the last upgrade (2.11.0-2.xenial -> 2.11.1-1.xenial), for whatever reason, either icinga is not setting the HOSTNAME environment variable any more when calling the script, or that script has newly acquired and enforcing a check for variable.

**Comment by tpo** [comment]
> However, for whatever reason, icinga did not log the problem.

The reason is this:

<pre>
$ /etc/icinga2/scripts/mail-service-notification.sh.orig -d 2019-11-27 -e fooservice -l fooserver -n FooServer -o "shit happened" -r sysmon@sourcepole.ch -s kaput -t alert -u FooService2
/etc/icinga2/scripts/mail-service-notification.sh.orig: 155: [: unexpected operator
$ echo $?
0
</pre>

Looks like dash is broken. No fault of icinga in this aspect.

**Comment by tpo** [comment]
> Looks like dash is broken.

No, it's not, it looks like this is common weird behavior:

<pre>
$ cat foo.sh 
#!/bin/bash

if [ x nonexistingoperator x ]; then
   echo this is unexpected
fi

echo still alive
$ ./foo.sh 
./foo.sh: line 3: [: nonexistingoperator: binary operator expected
still alive
$ echo $?
0
</pre>

@dnsmichi shall I file a new issue for the [HOSTNAME issue]( https://github.com/Icinga/icinga2/issues/7648#issuecomment-559042648)?

**Comment by dnsmichi** [comment]
Better create a PR if you're working on a fix already, don't need an extra issue for that.

**Comment by tpo** [comment]
it's weird that the HOSTNAME issue didn't hit us until recently because AFAICS the script was requiring that variable for a long time now. The variable wasn't set in our NotificationCommand definition. So I consider the issue resolved. Thanks a lot @dnsmichi and sorry for temporarily hijacking this issue @mcktr.

**Comment by vigiroux** [comment]
A trailing backslash '\' was dropped from the previous commit to mail-host-notification.sh around line 178, breaking the line continuation of the printf piped to MAILBIN for the debian case.  Seems like much overhead to create a new issue for this 1 char fix...

**Comment by dnsmichi** [comment]
> A trailing backslash '' was dropped from the previous commit to mail-host-notification.sh around line 178, breaking the line continuation of the printf piped to MAILBIN for the debian case. Seems like much overhead to create a new issue for this 1 char fix...

Can you please fix and send a PR?

**Comment by vigiroux** [comment]
Done. https://github.com/Icinga/icinga2/pull/7701

**Comment by mcktr** [comment]
Sorry I have to reopen this, the problems still exist in the master branch (with #7701 merged). 

The problem is that the recent changes are not compatible with Dash which is used by Debian and Ubuntu. For example `[[` and `<<<` are not available in Dash. Unfortunately I am not that savvy in Bash/Dash  to provide a implementation that is compatible across all supported operating systems and their shells. 

Having an eye on the 2.12.0 release I'll prepare a PR to revert the problematic changes.
