### ISSUE TITLE
service icinga2 reload fails on centos8

### ISSUE THREAD

**Issue by Sec42** [Icinga/icinga2#7920]
## Describe the bug

reloading icinga2 always fails on my Centos8 server

## To Reproduce

dnf install icinga2
service icinga2 start
service icinga2 reload

## Your Environment

* Version used (`icinga2 --version`):
reproduced with 2.11.2-1 and 2.11.3-1
* Operating System and version:
CentOS Linux release 8.1.1911 (Core) 

## Additional context

Seems to be an selinux issue:

-- Unit icinga2.service has begun reloading its configuration
Mar 17 16:40:59 cent8icinga.lab.neosit.com safe-reload[27871]: Validating config files: /usr/lib/icinga2/safe-reload: line 27: /tmp/tmp.WLj0d8OdJ3: Permission denied
Mar 17 16:40:59 cent8icinga.lab.neosit.com safe-reload[27871]: Failed

If I modify safe-reload to add "-x" and remove some error redirection:

Mar 17 16:45:46 cent8icinga.lab.neosit.com safe-reload[27960]: Validating config files: ++ mktemp
Mar 17 16:45:46 cent8icinga.lab.neosit.com safe-reload[27960]: + OUTPUTFILE=/tmp/tmp.v8bUoIH8dJ
Mar 17 16:45:46 cent8icinga.lab.neosit.com safe-reload[27960]: + type selinuxenabled
Mar 17 16:45:46 cent8icinga.lab.neosit.com safe-reload[27960]: + selinuxenabled
Mar 17 16:45:46 cent8icinga.lab.neosit.com safe-reload[27960]: + chcon -t icinga2_tmp_t /tmp/tmp.v8bUoIH8dJ
Mar 17 16:45:46 cent8icinga.lab.neosit.com safe-reload[27960]: chcon: failed to change context of '/tmp/tmp.v8bUoIH8dJ' to ‘system_u:object_r:icinga2_tmp_t:s0’: Invalid argument
Mar 17 16:45:46 cent8icinga.lab.neosit.com safe-reload[27960]: + /usr/sbin/icinga2 daemon --validate --color
Mar 17 16:45:46 cent8icinga.lab.neosit.com safe-reload[27960]: /usr/lib/icinga2/safe-reload: line 28: /tmp/tmp.v8bUoIH8dJ: Permission denied

**Comment by lippserd** [comment]
https://icinga.com/docs/icinga2/latest/doc/22-selinux/

**Comment by dgoetz** [comment]
This is an issue already fixed in https://github.com/Icinga/icinga2/pull/7858, but not released in form of a package for now as far as I know. You can build the policy which is already fixed on your own following the docs.

**Comment by Sec42** [comment]
To be honest, @lippserd I had not installed the icinga2-selinux package.

However, even after installing it, it is still broken on both CentOS 8 and RHEL 8.1 .

**Comment by lippserd** [comment]
> This is an issue already fixed in #7858, but not released in form of a package for now as far as I know. You can build the policy which is already fixed on your own following the docs.

This should be part of the 2.12.0 RC1 if I'm not mistaken. @Sec42 Sorry about that, feel free to test our release candidate and report back whether this fixes your issue.
